export default [{
  id: '1',
  role: 'Great Dictator',
  title: 'Good country seeks Glorious Leader',
  location: 'NK',
  employer: 'State run',
  shortDesc: 'Lorem ipsizzle dolizzle gizzle amizzle, fizzle adipiscing elizzle. Gangsta that\'s the shizzle velit, doggy crunk, bling bling quizzle, gravida yo mamma, my shizz.',
  longDesc: 'Etizzle laoreet urna ma nizzle nisl. Fo shizzle quizzle arcu. Break yo neck, yall i saw beyonces tizzles and my pizzle went crizzle, ipsum malesuada cool fo shizzle, fo shizzle mah nizzle fo rizzle, mah home g-dizzle fo shizzle my nizzle euismizzle fo shizzle, izzle luctizzle metizzle nulla izzle fo shizzle my nizzle. Vivamizzle ullamcorper, shut the shizzle up crunk varius things, nibh nunc cool dawg, bling bling daahng dawg leo elizzle uhuh ... yih! own yo\'. Maurizzle yippiyo, orci sizzle volutpizzle funky fresh, sizzle you son of a bizzle luctizzle nisi, at sizzle enizzle gangsta izzle bling bling. Nullam a gangster ac orci eleifend viverra. Phasellus ass i\'m in the shizzle. non fo shizzle vel pede phat facilisis. Brizzle sapizzle my shizz, iaculizzle fo shizzle, dawg sizzle, egestas doggy, erizzle. Nulla sizzle turpis break it down fizzle bibendum consequat. Nizzle pulvinizzle check out this pizzle. Aliquizzle erat volutpizzle. Nunc ut leo izzle dang pretizzle faucibus. Cras nizzle lacus fo dui condimentum yo. That\'s the shizzle nisl. Shiz et urna. Fo shizzle crackalackin ipsum fo shizzle mi. Fo ma nizzle turpis.',
  date: 1468085835677,
  pay: {
    range: {
      min: 35000,
      max: 45000,
    },
    desc: 'challenging',
  },
}, {
  id: '2',
  title: 'Experienced professional cuddler (remote)',
  role: 'Cuddler',
  location: '',
  employer: 'HUG',
  shortDesc: 'Lorem ipsizzle dolizzle gizzle amizzle, fizzle adipiscing elizzle. Gangsta that\'s the shizzle velit, doggy crunk, bling bling quizzle, gravida yo mamma, my shizz.',
  longDesc: 'Etizzle laoreet urna ma nizzle nisl. Fo shizzle quizzle arcu. Break yo neck, yall i saw beyonces tizzles and my pizzle went crizzle, ipsum malesuada cool fo shizzle, fo shizzle mah nizzle fo rizzle, mah home g-dizzle fo shizzle my nizzle euismizzle fo shizzle, izzle luctizzle metizzle nulla izzle fo shizzle my nizzle. Vivamizzle ullamcorper, shut the shizzle up crunk varius things, nibh nunc cool dawg, bling bling daahng dawg leo elizzle uhuh ... yih! own yo\'. Maurizzle yippiyo, orci sizzle volutpizzle funky fresh, sizzle you son of a bizzle luctizzle nisi, at sizzle enizzle gangsta izzle bling bling. Nullam a gangster ac orci eleifend viverra. Phasellus ass i\'m in the shizzle. non fo shizzle vel pede phat facilisis. Brizzle sapizzle my shizz, iaculizzle fo shizzle, dawg sizzle, egestas doggy, erizzle. Nulla sizzle turpis break it down fizzle bibendum consequat. Nizzle pulvinizzle check out this pizzle. Aliquizzle erat volutpizzle. Nunc ut leo izzle dang pretizzle faucibus. Cras nizzle lacus fo dui condimentum yo. That\'s the shizzle nisl. Shiz et urna. Fo shizzle crackalackin ipsum fo shizzle mi. Fo ma nizzle turpis.',
  date: 1468085835677,
  pay: {
    range: {
      min: 35000,
      max: 45000,
    },
    desc: 'challenging',
  },
},

{
  id: 3,
  title: 'Cozinheiro 3º',
  location: 'Castelo Branco',
  employer: 'centro social flor de oliveira',
  date: '11-12-2016',
  category: 'Hotelaria / Turismo',
},
{
  id: 4,
  title: 'Pintor Auto para oficina no Porto, Constituição',
  location: 'Porto',
  employer: 'mpna - auto',
  date: '11-12-2016',
  category: 'Conservação / Manutenção / Técnica',
},
{
  id: 5,
  title: 'Tech Recruiter',
  location: 'Lisboa',
  employer: 'landing.jobs',
  date: '11-12-2016',
  category: 'Gestão RH',
},
{
  id: 6,
  title: 'Estágio Financeiro para recém licenciados',
  location: 'Lisboa',
  employer: 'About Nav',
  date: '11-12-2016',
  category: 'Informática ( Analise de Sistemas )',
},
{
  id: 7,
  title: 'Consultores Funcionais Microsoft Dynamics NAV',
  location: 'Lisboa',
  employer: 'About Nav',
  date: '11-12-2016',
  category: 'Informática ( Analise de Sistemas )',
},
{
  id: 8,
  title: 'Operário Fabril - Algoz',
  location: 'Faro',
  employer: 'frutalcarmo, lda',
  date: '11-12-2016',
  category: 'Indústria / Produção',
},
{
  id: 9,
  title: 'Precisa-se de Padeiro para Viseu',
  location: 'Viseu',
  employer: 'bartolomeu & sacadura',
  date: '11-12-2016',
  category: 'Restauração / Bares',
},
{
  id: 10,
  title: 'Professores/Explicadores part-time ALVERCA DO RIBATEJO',
  location: 'Lisboa',
  employer: 'Cruzar Cenas, Lda.',
  date: '11-12-2016',
  category: 'Educação / Formação',
},
{
  id: 11,
  title: 'Comerciais para Castelo Branco,Covilhã e Guarda',
  location: 'Castelo Branco',
  employer: 'Nowo',
  date: '11-12-2016',
  category: 'Comercial / Vendas',
},
{
  id: 12,
  title: 'Optometrista - Paços de Ferreira (m/f)',
  location: 'Porto',
  employer: 'Grupo Labmed Saúde',
  date: '11-12-2016',
  category: 'Saúde / Medicina / Enfermagem',
},
{
  id: 13,
  title: 'Professor de Acordeão e ou Cavaquinho Almada',
  location: 'Setubal',
  employer: 'associação revolutionart',
  date: '11-12-2016',
  category: 'Educação / Formação',
},
{
  id: 14,
  title: 'Cozinheiro/a de 3º - Prática de almoços e petiscos',
  location: 'Lisboa',
  employer: 'rodrigues & vila, lda',
  date: '11-12-2016',
  category: 'Restauração / Bares',
},
{
  id: 15,
  title: 'Precisa-se Mecânico Automovel',
  location: 'Lisboa',
  employer: 'erguelop ii lda',
  date: '11-12-2016',
  category: 'Conservação / Manutenção / Técnica',
},
{
  id: 16,
  title: 'Professores de Francês',
  location: 'Viseu',
  employer: 'centro de estudos lamego',
  date: '11-12-2016',
  category: 'Educação / Formação',
},
{
  id: 17,
  title: 'Bate-Chapas Automóveis (m/f) - Lisboa',
  location: 'Lisboa',
  employer: 'Anónimo',
  date: '11-12-2016',
  category: 'Conservação / Manutenção / Técnica',
},
];
